const checkListData = {
  currentTab: "spring",
  checkList: {
    spring: {
      moneyCrop: [
        {
          season: "spring",
          section: "moneyCrop",
          label: "Potato",
          image: "Potato.png",
          wikiLink: "https://stardewvalleywiki.com/Potato",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "spring",
          section: "moneyCrop",
          label: "Strawberry",
          image: "Strawberry.png",
          wikiLink: "https://stardewvalleywiki.com/Strawberry",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
      farming: [
        {
          season: "spring",
          section: "farming",
          label: "Parsnip",
          image: "Parsnip.png",
          wikiLink: "https://stardewvalleywiki.com/Parsnip",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "spring",
          section: "farming",
          label: "Parsnip",
          image: "Parsnip.png",
          wikiLink: "https://stardewvalleywiki.com/Parsnip",
          quality: true,
          count: 5,
          completed: false,
        },
        {
          season: "spring",
          section: "farming",
          label: "Potato",
          image: "Potato.png",
          wikiLink: "https://stardewvalleywiki.com/Potato",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "spring",
          section: "farming",
          label: "Cauliflower",
          image: "Cauliflower.png",
          wikiLink: "https://stardewvalleywiki.com/Cauliflower",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "spring",
          section: "farming",
          label: "Green Bean",
          image: "Green_Bean.png",
          wikiLink: "https://stardewvalleywiki.com/Green_Bean",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
      foraging: [
        {
          season: "spring",
          section: "foraging",
          label: "Dandelion",
          image: "Dandelion.png",
          wikiLink: "https://stardewvalleywiki.com/Dandelion",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "spring",
          section: "foraging",
          label: "Leek",
          image: "Leek.png",
          wikiLink: "https://stardewvalleywiki.com/Leek",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "spring",
          section: "foraging",
          label: "Horseradish",
          image: "Wild_Horseradish.png",
          wikiLink: "https://stardewvalleywiki.com/Horseradish",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "spring",
          section: "foraging",
          label: "Daffodil",
          image: "Daffodil.png",
          wikiLink: "https://stardewvalleywiki.com/Daffodil",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
      fishing: [
        {
          season: "spring",
          section: "fishing",
          label: "Catfish",
          image: "Catfish.png",
          wikiLink: "https://stardewvalleywiki.com/Catfish",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "spring",
          section: "fishing",
          label: "Sardine",
          image: "Sardine.png",
          wikiLink: "https://stardewvalleywiki.com/Sardine",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "spring",
          section: "fishing",
          label: "Shad",
          image: "Shad.png",
          wikiLink: "https://stardewvalleywiki.com/Shad",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "spring",
          section: "fishing",
          label: "Sunfish",
          image: "Sunfish.png",
          wikiLink: "https://stardewvalleywiki.com/Sunfish",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
      other: [
        {
          season: "spring",
          section: "other",
          label: "Copper Pickaxe",
          image: "Copper_Pickaxe.png",
          wikiLink: "https://stardewvalleywiki.com/Pickaxes",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "spring",
          section: "other",
          label: "Copper Axe",
          image: "Copper_Axe.png",
          wikiLink: "https://stardewvalleywiki.com/Axes",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "spring",
          section: "other",
          label: "Barn",
          image: "Barn.png",
          wikiLink: "https://stardewvalleywiki.com/Barn",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "spring",
          section: "other",
          label: "Coop",
          image: "Coop.png",
          wikiLink: "https://stardewvalleywiki.com/Coop",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
    },
    summer: {
      moneyCrop: [
        {
          season: "summer",
          section: "moneyCrop",
          label: "Blueberry",
          image: "Blueberry.png",
          wikiLink: "https://stardewvalleywiki.com/Blueberry",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "summer",
          section: "moneyCrop",
          label: "Starfruit",
          image: "Starfruit.png",
          wikiLink: "https://stardewvalleywiki.com/Starfruit",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
      farming: [
        {
          season: "summer",
          section: "farming",
          label: "Hot Pepper",
          image: "Hot_Pepper.png",
          wikiLink: "https://stardewvalleywiki.com/Hot_Pepper",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "summer",
          section: "farming",
          label: "Melon",
          image: "Melon.png",
          wikiLink: "https://stardewvalleywiki.com/Melon",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "summer",
          section: "farming",
          label: "Melon",
          image: "Melon.png",
          wikiLink: "https://stardewvalleywiki.com/Melon",
          quality: true,
          count: 5,
          completed: false,
        },
        {
          season: "summer",
          section: "farming",
          label: "Wheat",
          image: "Wheat.png",
          wikiLink: "https://stardewvalleywiki.com/Wheat",
          quality: false,
          count: 10,
          completed: false,
        },
        {
          season: "summer",
          section: "farming",
          label: "Sunflower",
          image: "Sunflower.png",
          wikiLink: "https://stardewvalleywiki.com/Sunflower",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "summer",
          section: "farming",
          label: "Poppy",
          image: "Poppy.png",
          wikiLink: "https://stardewvalleywiki.com/Poppy",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
      foraging: [
        {
          season: "summer",
          section: "foraging",
          label: "Grape",
          image: "Grape.png",
          wikiLink: "https://stardewvalleywiki.com/Grape",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "summer",
          section: "foraging",
          label: "Spice Berry",
          image: "Spice_Berry.png",
          wikiLink: "https://stardewvalleywiki.com/Spice_Berry",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "summer",
          section: "foraging",
          label: "Sweet Pea",
          image: "Sweet_Pea.png",
          wikiLink: "https://stardewvalleywiki.com/Sweet_Pea",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "summer",
          section: "foraging",
          label: "Fiddlehead Fern",
          image: "Fiddlehead_Fern.png",
          wikiLink: "https://stardewvalleywiki.com/Fiddlehead_Fern",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
      fishing: [
        {
          season: "summer",
          section: "fishing",
          label: "Pufferfish",
          image: "Pufferfish.png",
          wikiLink: "https://stardewvalleywiki.com/Pufferfish",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "summer",
          section: "fishing",
          label: "Red Snapper",
          image: "Red_Snapper.png",
          wikiLink: "https://stardewvalleywiki.com/Red_Snapper",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "summer",
          section: "fishing",
          label: "Sturgeon",
          image: "Sturgeon.png",
          wikiLink: "https://stardewvalleywiki.com/Sturgeon",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "summer",
          section: "fishing",
          label: "Tuna",
          image: "Tuna.png",
          wikiLink: "https://stardewvalleywiki.com/Tuna",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
      other: [
        {
          season: "summer",
          section: "other",
          label: "Steel Pickaxe",
          image: "Steel_Pickaxe.png",
          wikiLink: "https://stardewvalleywiki.com/Pickaxes",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "summer",
          section: "other",
          label: "Steel Axe",
          image: "Steel_Axe.png",
          wikiLink: "https://stardewvalleywiki.com/Axes",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "summer",
          section: "other",
          label: "Pomegranate Sapling",
          image: "Pomegranate_Sapling.png",
          wikiLink: "https://stardewvalleywiki.com/Pomegranate_Sapling",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "summer",
          section: "other",
          label: "Apple Sapling",
          image: "Apple_Sapling.png",
          wikiLink: "https://stardewvalleywiki.com/Apple_Sapling",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "summer",
          section: "other",
          label: "Big Barn",
          image: "Big_Barn.png",
          wikiLink: "https://stardewvalleywiki.com/Big_Barn",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "summer",
          section: "other",
          label: "Big Coop",
          image: "Big_Coop.png",
          wikiLink: "https://stardewvalleywiki.com/Big_Coop",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
    },
    fall: {
      moneyCrop: [
        {
          season: "fall",
          section: "moneyCrop",
          label: "Cranberries",
          image: "Cranberries.png",
          wikiLink: "https://stardewvalleywiki.com/Cranberries",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
      farming: [
        {
          season: "fall",
          section: "farming",
          label: "Pumpkin",
          image: "Pumpkin.png",
          wikiLink: "https://stardewvalleywiki.com/Pumpkin",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "fall",
          section: "farming",
          label: "Yam",
          image: "Yam.png",
          wikiLink: "https://stardewvalleywiki.com/Yam",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "fall",
          section: "farming",
          label: "Corn",
          image: "Corn.png",
          wikiLink: "https://stardewvalleywiki.com/Corn",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "fall",
          section: "farming",
          label: "Corn",
          image: "Corn.png",
          wikiLink: "https://stardewvalleywiki.com/Corn",
          quality: true,
          count: 5,
          completed: false,
        },
        {
          season: "fall",
          section: "farming",
          label: "Eggplant",
          image: "Eggplant.png",
          wikiLink: "https://stardewvalleywiki.com/Eggplant",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
      foraging: [
        {
          season: "fall",
          section: "foraging",
          label: "Common Mushroom",
          image: "Common_Mushroom.png",
          wikiLink: "https://stardewvalleywiki.com/Common_Mushroom",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "fall",
          section: "foraging",
          label: "Hazelnut",
          image: "Hazelnut.png",
          wikiLink: "https://stardewvalleywiki.com/Hazelnut",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "fall",
          section: "foraging",
          label: "Wild Plum",
          image: "Wild_Plum.png",
          wikiLink: "https://stardewvalleywiki.com/Wild_Plum",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "fall",
          section: "foraging",
          label: "Blackberry",
          image: "Blackberry.png",
          wikiLink: "https://stardewvalleywiki.com/Blackberry",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
      fishing: [
        {
          season: "fall",
          section: "fishing",
          label: "Tiger Trout",
          image: "Tiger_Trout.png",
          wikiLink: "https://stardewvalleywiki.com/Tiger_Trout",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "fall",
          section: "fishing",
          label: "Walleye",
          image: "Walleye.png",
          wikiLink: "https://stardewvalleywiki.com/Walleye",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
      other: [
        {
          season: "fall",
          section: "other",
          label: "Gold Pickaxe",
          image: "Gold_Pickaxe.png",
          wikiLink: "https://stardewvalleywiki.com/Pickaxes",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "fall",
          section: "other",
          label: "Deluxe Barn",
          image: "Deluxe_Barn.png",
          wikiLink: "https://stardewvalleywiki.com/Deluxe_Barn",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "fall",
          section: "other",
          label: "Truffle",
          image: "Truffle.png",
          wikiLink: "https://stardewvalleywiki.com/Truffle",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "fall",
          section: "other",
          label: "Pomegranate",
          image: "Pomegranate.png",
          wikiLink: "https://stardewvalleywiki.com/Pomegranate",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "fall",
          section: "other",
          label: "Apple",
          image: "Apple.png",
          wikiLink: "https://stardewvalleywiki.com/Apple",
          quality: false,
          count: 4,
          completed: false,
        },
      ],
    },
    winter: {
      moneyCrop: [
        {
          season: "winter",
          section: "moneyCrop",
          label: "Starfruit",
          image: "Starfruit.png",
          wikiLink: "https://stardewvalleywiki.com/Starfruit",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "winter",
          section: "moneyCrop",
          label: "Ancient Fruit",
          image: "Ancient_Fruit.png",
          wikiLink: "https://stardewvalleywiki.com/Ancient_Fruit",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
      farming: [],
      foraging: [
        {
          season: "winter",
          section: "foraging",
          label: "Crystal Fruit",
          image: "Crystal_Fruit.png",
          wikiLink: "https://stardewvalleywiki.com/Crystal_Fruit",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "winter",
          section: "foraging",
          label: "Snow Yam",
          image: "Snow_Yam.png",
          wikiLink: "https://stardewvalleywiki.com/Snow_Yam",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "winter",
          section: "foraging",
          label: "Nautilus Shell",
          image: "Nautilus_Shell.png",
          wikiLink: "https://stardewvalleywiki.com/Nautilus_Shell",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "winter",
          section: "foraging",
          label: "Winter Root",
          image: "Winter_Root.png",
          wikiLink: "https://stardewvalleywiki.com/Winter_Root",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "winter",
          section: "foraging",
          label: "Crocus",
          image: "Crocus.png",
          wikiLink: "https://stardewvalleywiki.com/Crocus",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
      fishing: [],
      other: [
        {
          season: "winter",
          section: "other",
          label: "Iridium Pickaxe",
          image: "Iridium_Pickaxe.png",
          wikiLink: "https://stardewvalleywiki.com/Pickaxes",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "winter",
          section: "other",
          label: "Deluxe Coop",
          image: "Deluxe_Coop.png",
          wikiLink: "https://stardewvalleywiki.com/Deluxe_Coop",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "winter",
          section: "other",
          label: "Rabbits Foot",
          image: "Rabbits_Foot.png",
          wikiLink: "https://stardewvalleywiki.com/Rabbits_Foot",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
    },
    anytime: {
      mining: [
        {
          season: "anytime",
          section: "mining",
          label: "Copper Bar",
          image: "Copper_Bar.png",
          wikiLink: "https://stardewvalleywiki.com/Copper_Bar",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "mining",
          label: "Iron Bar",
          image: "Iron_Bar.png",
          wikiLink: "https://stardewvalleywiki.com/Iron_Bar",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "mining",
          label: "Gold Bar",
          image: "Gold_Bar.png",
          wikiLink: "https://stardewvalleywiki.com/Gold_Bar",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "mining",
          label: "Frozen Tear",
          image: "Frozen_Tear.png",
          wikiLink: "https://stardewvalleywiki.com/Frozen_Tear",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "mining",
          label: "Earth Crystal",
          image: "Earth_Crystal.png",
          wikiLink: "https://stardewvalleywiki.com/Earth_Crystal",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "mining",
          label: "Quartz",
          image: "Quartz.png",
          wikiLink: "https://stardewvalleywiki.com/Quartz",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "mining",
          label: "Fire Quartz",
          image: "Fire_Quartz.png",
          wikiLink: "https://stardewvalleywiki.com/Fire_Quartz",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "mining",
          label: "Frozen Geode",
          image: "Frozen_Geode.png",
          wikiLink: "https://stardewvalleywiki.com/Frozen_Geode",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "mining",
          label: "Aquamarine",
          image: "Aquamarine.png",
          wikiLink: "https://stardewvalleywiki.com/Aquamarine",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "mining",
          label: "Bat Wing",
          image: "Bat_Wing.png",
          wikiLink: "https://stardewvalleywiki.com/Bat_Wing",
          quality: false,
          count: 10,
          completed: false,
        },
        {
          season: "anytime",
          section: "mining",
          label: "Solar Essence",
          image: "Solar_Essence.png",
          wikiLink: "https://stardewvalleywiki.com/Solar_Essence",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "mining",
          label: "Purple Mushroom",
          image: "Purple_Mushroom.png",
          wikiLink: "https://stardewvalleywiki.com/Purple_Mushroom",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "mining",
          label: "Red Mushroom",
          image: "Red_Mushroom.png",
          wikiLink: "https://stardewvalleywiki.com/Red_Mushroom",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
      fishing: [
        {
          season: "anytime",
          section: "fishing",
          label: "Bream",
          image: "Bream.png",
          wikiLink: "https://stardewvalleywiki.com/Bream",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "fishing",
          label: "Largemouth Bass",
          image: "Largemouth_Bass.png",
          wikiLink: "https://stardewvalleywiki.com/Largemouth_Bass",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "fishing",
          label: "Bullhead",
          image: "Bullhead.png",
          wikiLink: "https://stardewvalleywiki.com/Bullhead",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "fishing",
          label: "Chub",
          image: "Chub.png",
          wikiLink: "https://stardewvalleywiki.com/Chub",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "fishing",
          label: "Ghostfish",
          image: "Ghostfish.png",
          wikiLink: "https://stardewvalleywiki.com/Ghostfish",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "fishing",
          label: "Sandfish",
          image: "Sandfish.png",
          wikiLink: "https://stardewvalleywiki.com/Sandfish",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "fishing",
          label: "Woodskip",
          image: "Woodskip.png",
          wikiLink: "https://stardewvalleywiki.com/Woodskip",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
      crabPot: [
        {
          season: "anytime",
          section: "crabPot",
          label: "Cockle",
          image: "Cockle.png",
          wikiLink: "https://stardewvalleywiki.com/Cockle",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "crabPot",
          label: "Mussel",
          image: "Mussel.png",
          wikiLink: "https://stardewvalleywiki.com/Mussel",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "crabPot",
          label: "Oyster",
          image: "Oyster.png",
          wikiLink: "https://stardewvalleywiki.com/Oyster",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "crabPot",
          label: "Clam",
          image: "Clam.png",
          wikiLink: "https://stardewvalleywiki.com/Clam",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "crabPot",
          label: "Periwinkle",
          image: "Periwinkle.png",
          wikiLink: "https://stardewvalleywiki.com/Periwinkle",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
      exoticForaging: [
        {
          season: "anytime",
          section: "exoticForaging",
          label: "Oak Resin",
          image: "Oak_Resin.png",
          wikiLink: "https://stardewvalleywiki.com/Oak_Resin",
          quality: false,
          count: 2,
          completed: false,
        },
        {
          season: "anytime",
          section: "exoticForaging",
          label: "Pine Tar",
          image: "Pine_Tar.png",
          wikiLink: "https://stardewvalleywiki.com/Pine_Tar",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "exoticForaging",
          label: "Maple Syrup",
          image: "Maple_Syrup.png",
          wikiLink: "https://stardewvalleywiki.com/Maple_Syrup",
          quality: false,
          count: 2,
          completed: false,
        },
        {
          season: "anytime",
          section: "exoticForaging",
          label: "Coconut",
          image: "Coconut.png",
          wikiLink: "https://stardewvalleywiki.com/Coconut",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "exoticForaging",
          label: "Cave Carrot",
          image: "Cave_Carrot.png",
          wikiLink: "https://stardewvalleywiki.com/Cave_Carrot",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
      construction: [
        {
          season: "anytime",
          section: "construction",
          label: "Wood",
          image: "Wood.png",
          wikiLink: "https://stardewvalleywiki.com/Wood",
          quality: false,
          count: 198,
          completed: false,
        },
        {
          season: "anytime",
          section: "construction",
          label: "Stone",
          image: "Stone.png",
          wikiLink: "https://stardewvalleywiki.com/Stone",
          quality: false,
          count: 99,
          completed: false,
        },
        {
          season: "anytime",
          section: "construction",
          label: "Hardwood",
          image: "Hardwood.png",
          wikiLink: "https://stardewvalleywiki.com/Hardwood",
          quality: false,
          count: 10,
          completed: false,
        },
      ],
      animals: [
        {
          season: "anytime",
          section: "animals",
          label: "Large Brown Egg",
          image: "Large_Brown_Egg.png",
          wikiLink: "https://stardewvalleywiki.com/Large_Egg",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "animals",
          label: "Large Egg",
          image: "Large_Egg.png",
          wikiLink: "https://stardewvalleywiki.com/Large_Egg",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "animals",
          label: "Duck Egg",
          image: "Duck_Egg.png",
          wikiLink: "https://stardewvalleywiki.com/Duck_Egg",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "animals",
          label: "Duck Feather",
          image: "Duck_Feather.png",
          wikiLink: "https://stardewvalleywiki.com/Duck_Feather",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "animals",
          label: "Large Milk",
          image: "Large_Milk.png",
          wikiLink: "https://stardewvalleywiki.com/Large_Milk",
          quality: false,
          count: 10,
          completed: false,
        },
        {
          season: "anytime",
          section: "animals",
          label: "Large Goat Milk",
          image: "Large_Goat_Milk.png",
          wikiLink: "https://stardewvalleywiki.com/Large_Goat_Milk",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
      artisan: [
        {
          season: "anytime",
          section: "artisan",
          label: "Honey",
          image: "Honey.png",
          wikiLink: "https://stardewvalleywiki.com/Honey",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "artisan",
          label: "Jelly",
          image: "Jelly.png",
          wikiLink: "https://stardewvalleywiki.com/Jelly",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "artisan",
          label: "Cheese",
          image: "Cheese.png",
          wikiLink: "https://stardewvalleywiki.com/Cheese",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "artisan",
          label: "Cloth",
          image: "Cloth.png",
          wikiLink: "https://stardewvalleywiki.com/Cloth",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
      bulletinBoard: [
        {
          season: "anytime",
          section: "bulletinBoard",
          label: "Kitchen (needed for cooking)",
          image: "Kitchen.png",
          wikiLink: "https://stardewvalleywiki.com/Kitchen",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "bulletinBoard",
          label: "Maki Roll",
          image: "Maki_Roll.png",
          wikiLink: "https://stardewvalleywiki.com/Maki_Roll",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "bulletinBoard",
          label: "Omelet",
          image: "Omelet.png",
          wikiLink: "https://stardewvalleywiki.com/Omelet",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "bulletinBoard",
          label: "Hay",
          image: "Hay.png",
          wikiLink: "https://stardewvalleywiki.com/Hay",
          quality: false,
          count: 10,
          completed: false,
        },
        {
          season: "anytime",
          section: "bulletinBoard",
          label: "Wine",
          image: "Wine.png",
          wikiLink: "https://stardewvalleywiki.com/Wine",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "bulletinBoard",
          label: "Sea Urchin",
          image: "Sea_Urchin.png",
          wikiLink: "https://stardewvalleywiki.com/Sea_Urchin",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
      vault: [
        {
          season: "anytime",
          section: "vault",
          label: "2,500g Bundle",
          image: "2500_Bundle.png",
          wikiLink: "https://stardewvalleywiki.com/Bundles#Vault",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "vault",
          label: "5,000g Bundle",
          image: "5000_Bundle.png",
          wikiLink: "https://stardewvalleywiki.com/Bundles#Vault",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "vault",
          label: "10,000g Bundle",
          image: "10000_Bundle.png",
          wikiLink: "https://stardewvalleywiki.com/Bundles#Vault",
          quality: false,
          count: 1,
          completed: false,
        },
        {
          season: "anytime",
          section: "vault",
          label: "25,000g Bundle",
          image: "25000_Bundle.png",
          wikiLink: "https://stardewvalleywiki.com/Bundles#Vault",
          quality: false,
          count: 1,
          completed: false,
        },
      ],
    },
  },
};

export default checkListData;
